"use client";
import {useState} from "react";
import {ArrowRight,Bell,BriefcaseBusiness,CalendarDays,CheckCircle2,ChevronDown,ClipboardCheck,Clock3,Coins,ExternalLink,Gauge,LineChart,Menu,MoreHorizontal,PackageOpen,Pencil,Search,Share2,Sparkles,Target,TrendingUp,UsersRound,WalletCards,X} from "lucide-react";
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";

const data={
 talent:{name:"TALENT-ON",url:"https://talent.leyva-dev.es",ready:true,sub:"Personas · Equipos · Costes",color:"#8b5cf6",soft:"#f3efff",icon:UsersRound,stats:[["Empleados activos","86","+4 este mes"],["Vacantes abiertas","12","5 prioritarias"],["Coste de personal","148.420 €","+2,8% vs. julio"],["Rentabilidad equipos","71%","+3,2 puntos"]]},
 growth:{name:"GROWTH-ON",url:"https://growth.leyva-dev.es",ready:true,sub:"Clientes · Ventas · Canales",color:"#0ea5e9",soft:"#eaf8ff",icon:TrendingUp,stats:[["Oportunidades","247","+18% vs. julio"],["Ventas cerradas","64","25,9% conversión"],["Ingresos generados","286.900 €","+11,4% vs. julio"],["Actividad agentes","83%","+6,1 puntos"]]},
 finance:{name:"FINANCE-ON",url:"https://finance.leyva-dev.es",ready:true,sub:"Tesorería · Resultados · Control",color:"#10b981",soft:"#eafbf5",icon:WalletCards,stats:[["Saldo disponible","412.680 €","+8,2% vs. julio"],["Cobros pendientes","94.320 €","18 facturas"],["Pagos próximos","71.540 €","Próximos 15 días"],["Margen operativo","23,8%","+1,7 puntos"]]},
 social:{name:"SOCIAL-ON",url:"https://social.leyva-dev.es",ready:true,sub:"Redes · Audiencias · Contenido",color:"#f97316",soft:"#fff4e9",icon:Share2,stats:[["Estado","Operativo","Acceso disponible"],["Salud web","Activa","Seguimiento por empresa"],["Redes sociales","Activas","Audiencia y rendimiento"],["Informes IA","Disponible","Resumen bajo consulta"]]},
 task:{name:"TASK-ON",url:"https://app.task-on.es/Dashboard",ready:true,sub:"Tareas · Proyectos · Seguimiento",color:"#6366f1",soft:"#eef0ff",icon:ClipboardCheck,stats:[["Estado","Operativo","Acceso disponible"],["Tareas","Centralizadas","Seguimiento del equipo"],["Proyectos","Activos","Control de avances"],["Responsables","Asignados","Prioridades y plazos"]]},
 product:{name:"PRODUCT-ON",url:"https://product.leyva-dev.es/",ready:true,sub:"Productos · Proveedores · Catálogo",color:"#ec4899",soft:"#fff0f7",icon:PackageOpen,stats:[["Acceso","Disponible","Gestión de productos"],["Productos","Consultar","Catálogo y fichas"],["Proveedores","Consultar","Contactos y documentación"],["Proyectos","Consultar","Seguimiento y entregables"]]}
};
type Objective={id:string;label:string;current:number;target:number;unit:string;source:string};
type CompanyGoal={id:string;name:string;current:number;target:number;unit:string};
const initialObjectives:Objective[]=[
 {id:"sales",label:"Ventas cerradas",current:64,target:80,unit:"",source:"GROWTH-ON"},
 {id:"opportunities",label:"Oportunidades",current:247,target:300,unit:"",source:"GROWTH-ON"},
 {id:"coverage",label:"Vacantes críticas cubiertas",current:5,target:8,unit:"",source:"TALENT-ON"},
 {id:"margin",label:"Margen operativo",current:23.8,target:25,unit:"%",source:"FINANCE-ON"}
];
const initialCompanyGoals:CompanyGoal[]=[
 {id:"leyva",name:"Leyva Marroquinería",current:142800,target:155000,unit:"€"},
 {id:"linmania",name:"Linmania",current:96400,target:110000,unit:"€"},
 {id:"rockstar",name:"Rockstar Benidorm",current:63200,target:85000,unit:"€"},
 {id:"contact",name:"Contact-ON",current:48500,target:60000,unit:"€"}
];
const companies=[["Leyva Marroquinería","72","142.800 €","29,4%","ok"],["Linmania","68","96.400 €","21,7%","ok"],["Rockstar Benidorm","54","63.200 €","14,2%","warn"],["Contact-ON","61","48.500 €","18,6%","ok"]];
const pct=(current:number,target:number)=>Math.min(Math.round((current/Math.max(target,1))*100),999);
const tone=(value:number)=>value>=90?"good":value>=70?"watch":"risk";
const formatValue=(value:number,unit:string)=>unit==="€"?`${value.toLocaleString("es-ES")} €`:`${value.toLocaleString("es-ES")}${unit}`;
function Trend({color}:{color:string}){return <svg viewBox="0 0 120 38" className="trend"><path d="M2 33C18 30 18 20 34 23S53 31 66 17S88 20 100 9S111 8 118 3" fill="none" stroke={color} strokeWidth="3" strokeLinecap="round"/><path d="M2 33C18 30 18 20 34 23S53 31 66 17S88 20 100 9S111 8 118 3V38H2Z" fill={color} opacity=".08"/></svg>}

export default function Home(){
 const[menu,setMenu]=useState(false),[alerts,setAlerts]=useState(3),[period,setPeriod]=useState("Este mes"),[editing,setEditing]=useState(false);
 const[objectives,setObjectives]=useState(initialObjectives),[companyGoals,setCompanyGoals]=useState(initialCompanyGoals);
 const[draftObjectives,setDraftObjectives]=useState(initialObjectives),[draftCompanyGoals,setDraftCompanyGoals]=useState(initialCompanyGoals);
 const openEditor=()=>{setDraftObjectives(objectives.map(x=>({...x})));setDraftCompanyGoals(companyGoals.map(x=>({...x})));setEditing(true)};
 const saveGoals=()=>{setObjectives(draftObjectives);setCompanyGoals(draftCompanyGoals);setEditing(false)};
 return <main>
 <aside className={menu?"side open":"side"}><div className="brand"><div><strong>ON</strong><small>LEYVAGROUP</small></div><button onClick={()=>setMenu(false)}><X/></button></div><nav><p>PLATAFORMAS</p><a href="https://talent.leyva-dev.es"><i className="purple"/>TALENT-ON<ExternalLink/></a><a href="https://growth.leyva-dev.es"><i className="blue"/>GROWTH-ON<ExternalLink/></a><a href="https://finance.leyva-dev.es"><i className="green"/>FINANCE-ON<ExternalLink/></a><a href="https://social.leyva-dev.es"><i className="orange"/>SOCIAL-ON<ExternalLink/></a><a href={data.product.url}><i className="pink"/>PRODUCT-ON<ExternalLink/></a><p>CONTROL</p><a href="/objetivos-2026/"><Target/>OBJETIVOS 2026<ExternalLink/></a><a href="https://app.task-on.es/Dashboard"><i className="indigo"/>TASK-ON<ExternalLink/></a><a href="#alertas"><Bell/>Alertas<span>{alerts}</span></a></nav><div className="sideBottom"><div className="sync"><CheckCircle2/>Datos sincronizados<small>Hoy, 10:42</small></div><div className="user"><b>DL</b><div><strong>David Leyva</strong><small>Superusuario</small></div><MoreHorizontal/></div></div></aside>
 <section className="workspace" id="resumen"><header><button className="hamb" onClick={()=>setMenu(true)}><Menu/></button><label className="search"><Search/><input placeholder="Buscar empresas, personas, métricas..."/><kbd>⌘ K</kbd></label><div className="headRight"><button onClick={()=>setAlerts(0)} className="bell"><Bell/>{alerts>0&&<i/>}</button><b>DL</b><ChevronDown/></div></header>
 <div className="content"><div className="heading"><div><small>MIÉRCOLES, 26 DE AGOSTO</small><h1>Buenos días, David</h1><p>Esta es la situación global de LeyvaGroup.</p></div><label><CalendarDays/><select value={period} onChange={e=>setPeriod(e.target.value)}><option>Este mes</option><option>Últimos 30 días</option><option>Este trimestre</option></select></label></div>
 <section className="global"><div><span>Ingresos consolidados</span><strong>591.800 €</strong><em><TrendingUp/>12,4%</em></div><div><span>Resultado operativo</span><strong>140.850 €</strong><em><TrendingUp/>8,7%</em></div><div><span>Personas activas</span><strong>86</strong><small>4 nuevas</small></div><div><span>Salud del grupo</span><strong>82 <small>/ 100</small></strong><i className="ring">82%</i></div></section>
 <section className="goalsPanel" id="objetivos"><div className="goalsHead"><div><span className="eyebrow">OBJETIVOS DEL PERIODO</span><h2>Resultado actual frente a objetivo</h2><p>Los resultados proceden de cada plataforma. Los objetivos se definen desde ON.</p></div><button onClick={openEditor}><Pencil/>Configurar objetivos</button></div><div className="goalGrid">{objectives.map(item=>{const progress=pct(item.current,item.target);return <div className="goal" key={item.id}><div className="goalTop"><span>{item.label}</span><small>{item.source}</small></div><div className="goalNumbers"><strong>{formatValue(item.current,item.unit)}</strong><span>de {formatValue(item.target,item.unit)}</span><b className={tone(progress)}>{progress}%</b></div><div className="goalBar"><i className={tone(progress)} style={{width:`${Math.min(progress,100)}%`}}/></div></div>})}</div><div className="companyGoalHead"><h3>Objetivo principal por empresa</h3><span>Resultado / meta del mes</span></div><div className="companyGoals">{companyGoals.map(item=>{const progress=pct(item.current,item.target);return <div key={item.id}><span>{item.name}</span><strong>{progress}%</strong><div className="miniBar"><i className={tone(progress)} style={{width:`${Math.min(progress,100)}%`}}/></div><small>{formatValue(item.current,item.unit)} / {formatValue(item.target,item.unit)}</small></div>})}</div></section>
 <Tabs defaultValue="global" className="tabs"><TabsList><TabsTrigger value="global">Visión global</TabsTrigger><TabsTrigger value="performance">Rendimiento</TabsTrigger><TabsTrigger value="actions">Alertas y acciones</TabsTrigger></TabsList><TabsContent value="global">
 <section className="cards">{Object.entries(data).filter(([key])=>key!=="task").map(([key,p])=>{const Icon=p.icon;return <article id={key} key={key} className="" style={{"--c":p.color,"--soft":p.soft} as React.CSSProperties}><div className="cardHead"><b><Icon/></b><div><h2><a href={p.url || "#product"} style={{color:"inherit",textDecoration:"none"}}>{p.name}</a></h2><p>{p.sub}</p></div><MoreHorizontal/></div>{p.ready?<><div className="mainKpi"><div><span>{p.stats[0][0]}</span><strong>{p.stats[0][1]}</strong><small>{p.stats[0][2]}</small></div><Trend color={p.color}/></div><div className="substats">{p.stats.slice(1).map(s=><div key={s[0]}><span>{s[0]}</span><strong>{s[1]}</strong><small>{s[2]}</small></div>)}</div><button onClick={()=>window.location.href=p.url}>Abrir {p.name}<ArrowRight/></button></>:<div className="comingBody"><strong>Productos y proveedores</strong><p>Falta configurar la URL de acceso a PRODUCT-ON.</p></div>}</article>})}</section>
 <section className="lower"><article className="panel" id="empresas"><div className="panelHead"><div><h2>Rendimiento por empresa</h2><p>Comparativa consolidada de las tres plataformas</p></div><button>Ver informe <ArrowRight/></button></div><div className="table"><div className="row labels"><span>Empresa</span><span>Salud</span><span>Ingresos</span><span>Margen</span></div>{companies.map(c=><div className="row" key={c[0]}><strong><i className={c[4]}/>{c[0]}</strong><span><b><i style={{width:c[1]+"%"}}/></b>{c[1]}%</span><span>{c[2]}</span><span>{c[3]}</span></div>)}</div></article>
 <article className="panel alerts" id="alertas"><div className="panelHead"><div><h2>Requiere atención</h2><p>Prioridades detectadas automáticamente</p></div><mark>3</mark></div><Alert icon={<Clock3/>} toneName="amber" title="5 vacantes prioritarias" text="Dos llevan más de 20 días abiertas." app="TALENT-ON"/><Alert icon={<Coins/>} toneName="red" title="18 cobros vencidos" text="Importe pendiente: 94.320 €." app="FINANCE-ON"/><Alert icon={<Target/>} toneName="blue" title="Conversión bajo el objetivo" text="Rockstar Benidorm está en 14,2%." app="GROWTH-ON"/></article></section>
 </TabsContent><TabsContent value="performance"><Empty icon={<LineChart/>} title="Rendimiento consolidado" text="Cruce de equipos, ventas y margen para detectar qué áreas generan más rentabilidad."/></TabsContent><TabsContent value="actions"><Empty icon={<Sparkles/>} title="Centro de decisiones" text="Prioridades ordenadas por impacto económico y urgencia, con acceso directo al módulo responsable."/></TabsContent></Tabs></div></section>
 {editing&&<div className="modalBackdrop" onMouseDown={()=>setEditing(false)}><section className="goalModal" role="dialog" aria-modal="true" aria-labelledby="goal-title" onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><div><span className="eyebrow">CONFIGURACIÓN</span><h2 id="goal-title">Objetivos de {period.toLowerCase()}</h2><p>Modifica las metas. Los resultados actuales se sincronizan automáticamente.</p></div><button onClick={()=>setEditing(false)}><X/></button></div><div className="modalBody"><h3>Objetivos globales</h3>{draftObjectives.map((item,index)=><label key={item.id}><span>{item.label}<small>{item.source}</small></span><input type="number" min="0" step={item.unit==="%"?"0.1":"1"} value={item.target} onChange={e=>setDraftObjectives(items=>items.map((row,i)=>i===index?{...row,target:Number(e.target.value)}:row))}/><b>{item.unit}</b></label>)}<h3>Objetivo principal por empresa</h3>{draftCompanyGoals.map((item,index)=><label key={item.id}><span>{item.name}<small>Facturación objetivo</small></span><input type="number" min="0" step="100" value={item.target} onChange={e=>setDraftCompanyGoals(items=>items.map((row,i)=>i===index?{...row,target:Number(e.target.value)}:row))}/><b>€</b></label>)}</div><div className="modalActions"><button onClick={()=>setEditing(false)}>Cancelar</button><button onClick={saveGoals}>Guardar objetivos</button></div></section></div>}
 </main>}
function Alert({icon,toneName,title,text,app}:{icon:React.ReactNode;toneName:string;title:string;text:string;app:string}){return <div className={`alert ${toneName}`}><b>{icon}</b><div><strong>{title}</strong><p>{text}</p><small>{app}</small></div><ArrowRight/></div>}
function Empty({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="empty">{icon}<h2>{title}</h2><p>{text}</p></div>}
